// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddPathMapping(arg1:string,arg2:string):Promise<void>;

export function CheckConnection():Promise<boolean>;

export function GetConfig():Promise<config.Config>;

export function GetPathMappings():Promise<{[key: string]: string}>;

export function GetStatus():Promise<{[key: string]: any}>;

export function RemovePathMapping(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SyncNow():Promise<void>;

export function TogglePause():Promise<boolean>;
