// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPathMapping(arg1, arg2) {
  return window['go']['main']['App']['AddPathMapping'](arg1, arg2);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPathMappings() {
  return window['go']['main']['App']['GetPathMappings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function RemovePathMapping(arg1) {
  return window['go']['main']['App']['RemovePathMapping'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
